// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package wasmextensionv1

import (
	_ "cosmossdk.io/api/amino"
	_ "cosmossdk.io/api/cosmos/base/v1beta1"
	_ "cosmossdk.io/api/cosmos/msg/v1"
	v1 "cosmossdk.io/api/cosmwasm/wasm/v1"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_MsgStoreCodeAdmin                        protoreflect.MessageDescriptor
	fd_MsgStoreCodeAdmin_authority              protoreflect.FieldDescriptor
	fd_MsgStoreCodeAdmin_creator                protoreflect.FieldDescriptor
	fd_MsgStoreCodeAdmin_wasm_byte_code         protoreflect.FieldDescriptor
	fd_MsgStoreCodeAdmin_instantiate_permission protoreflect.FieldDescriptor
)

func init() {
	file_miniwasm_wasmextension_v1_tx_proto_init()
	md_MsgStoreCodeAdmin = File_miniwasm_wasmextension_v1_tx_proto.Messages().ByName("MsgStoreCodeAdmin")
	fd_MsgStoreCodeAdmin_authority = md_MsgStoreCodeAdmin.Fields().ByName("authority")
	fd_MsgStoreCodeAdmin_creator = md_MsgStoreCodeAdmin.Fields().ByName("creator")
	fd_MsgStoreCodeAdmin_wasm_byte_code = md_MsgStoreCodeAdmin.Fields().ByName("wasm_byte_code")
	fd_MsgStoreCodeAdmin_instantiate_permission = md_MsgStoreCodeAdmin.Fields().ByName("instantiate_permission")
}

var _ protoreflect.Message = (*fastReflection_MsgStoreCodeAdmin)(nil)

type fastReflection_MsgStoreCodeAdmin MsgStoreCodeAdmin

func (x *MsgStoreCodeAdmin) ProtoReflect() protoreflect.Message {
	return (*fastReflection_MsgStoreCodeAdmin)(x)
}

func (x *MsgStoreCodeAdmin) slowProtoReflect() protoreflect.Message {
	mi := &file_miniwasm_wasmextension_v1_tx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_MsgStoreCodeAdmin_messageType fastReflection_MsgStoreCodeAdmin_messageType
var _ protoreflect.MessageType = fastReflection_MsgStoreCodeAdmin_messageType{}

type fastReflection_MsgStoreCodeAdmin_messageType struct{}

func (x fastReflection_MsgStoreCodeAdmin_messageType) Zero() protoreflect.Message {
	return (*fastReflection_MsgStoreCodeAdmin)(nil)
}
func (x fastReflection_MsgStoreCodeAdmin_messageType) New() protoreflect.Message {
	return new(fastReflection_MsgStoreCodeAdmin)
}
func (x fastReflection_MsgStoreCodeAdmin_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_MsgStoreCodeAdmin
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_MsgStoreCodeAdmin) Descriptor() protoreflect.MessageDescriptor {
	return md_MsgStoreCodeAdmin
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_MsgStoreCodeAdmin) Type() protoreflect.MessageType {
	return _fastReflection_MsgStoreCodeAdmin_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_MsgStoreCodeAdmin) New() protoreflect.Message {
	return new(fastReflection_MsgStoreCodeAdmin)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_MsgStoreCodeAdmin) Interface() protoreflect.ProtoMessage {
	return (*MsgStoreCodeAdmin)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_MsgStoreCodeAdmin) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Authority != "" {
		value := protoreflect.ValueOfString(x.Authority)
		if !f(fd_MsgStoreCodeAdmin_authority, value) {
			return
		}
	}
	if x.Creator != "" {
		value := protoreflect.ValueOfString(x.Creator)
		if !f(fd_MsgStoreCodeAdmin_creator, value) {
			return
		}
	}
	if len(x.WasmByteCode) != 0 {
		value := protoreflect.ValueOfBytes(x.WasmByteCode)
		if !f(fd_MsgStoreCodeAdmin_wasm_byte_code, value) {
			return
		}
	}
	if x.InstantiatePermission != nil {
		value := protoreflect.ValueOfMessage(x.InstantiatePermission.ProtoReflect())
		if !f(fd_MsgStoreCodeAdmin_instantiate_permission, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_MsgStoreCodeAdmin) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdmin.authority":
		return x.Authority != ""
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdmin.creator":
		return x.Creator != ""
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdmin.wasm_byte_code":
		return len(x.WasmByteCode) != 0
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdmin.instantiate_permission":
		return x.InstantiatePermission != nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: miniwasm.wasmextension.v1.MsgStoreCodeAdmin"))
		}
		panic(fmt.Errorf("message miniwasm.wasmextension.v1.MsgStoreCodeAdmin does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MsgStoreCodeAdmin) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdmin.authority":
		x.Authority = ""
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdmin.creator":
		x.Creator = ""
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdmin.wasm_byte_code":
		x.WasmByteCode = nil
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdmin.instantiate_permission":
		x.InstantiatePermission = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: miniwasm.wasmextension.v1.MsgStoreCodeAdmin"))
		}
		panic(fmt.Errorf("message miniwasm.wasmextension.v1.MsgStoreCodeAdmin does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_MsgStoreCodeAdmin) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdmin.authority":
		value := x.Authority
		return protoreflect.ValueOfString(value)
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdmin.creator":
		value := x.Creator
		return protoreflect.ValueOfString(value)
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdmin.wasm_byte_code":
		value := x.WasmByteCode
		return protoreflect.ValueOfBytes(value)
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdmin.instantiate_permission":
		value := x.InstantiatePermission
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: miniwasm.wasmextension.v1.MsgStoreCodeAdmin"))
		}
		panic(fmt.Errorf("message miniwasm.wasmextension.v1.MsgStoreCodeAdmin does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MsgStoreCodeAdmin) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdmin.authority":
		x.Authority = value.Interface().(string)
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdmin.creator":
		x.Creator = value.Interface().(string)
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdmin.wasm_byte_code":
		x.WasmByteCode = value.Bytes()
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdmin.instantiate_permission":
		x.InstantiatePermission = value.Message().Interface().(*v1.AccessConfig)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: miniwasm.wasmextension.v1.MsgStoreCodeAdmin"))
		}
		panic(fmt.Errorf("message miniwasm.wasmextension.v1.MsgStoreCodeAdmin does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MsgStoreCodeAdmin) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdmin.instantiate_permission":
		if x.InstantiatePermission == nil {
			x.InstantiatePermission = new(v1.AccessConfig)
		}
		return protoreflect.ValueOfMessage(x.InstantiatePermission.ProtoReflect())
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdmin.authority":
		panic(fmt.Errorf("field authority of message miniwasm.wasmextension.v1.MsgStoreCodeAdmin is not mutable"))
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdmin.creator":
		panic(fmt.Errorf("field creator of message miniwasm.wasmextension.v1.MsgStoreCodeAdmin is not mutable"))
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdmin.wasm_byte_code":
		panic(fmt.Errorf("field wasm_byte_code of message miniwasm.wasmextension.v1.MsgStoreCodeAdmin is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: miniwasm.wasmextension.v1.MsgStoreCodeAdmin"))
		}
		panic(fmt.Errorf("message miniwasm.wasmextension.v1.MsgStoreCodeAdmin does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_MsgStoreCodeAdmin) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdmin.authority":
		return protoreflect.ValueOfString("")
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdmin.creator":
		return protoreflect.ValueOfString("")
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdmin.wasm_byte_code":
		return protoreflect.ValueOfBytes(nil)
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdmin.instantiate_permission":
		m := new(v1.AccessConfig)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: miniwasm.wasmextension.v1.MsgStoreCodeAdmin"))
		}
		panic(fmt.Errorf("message miniwasm.wasmextension.v1.MsgStoreCodeAdmin does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_MsgStoreCodeAdmin) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in miniwasm.wasmextension.v1.MsgStoreCodeAdmin", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_MsgStoreCodeAdmin) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MsgStoreCodeAdmin) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_MsgStoreCodeAdmin) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_MsgStoreCodeAdmin) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*MsgStoreCodeAdmin)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Authority)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Creator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.WasmByteCode)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.InstantiatePermission != nil {
			l = options.Size(x.InstantiatePermission)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*MsgStoreCodeAdmin)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.InstantiatePermission != nil {
			encoded, err := options.Marshal(x.InstantiatePermission)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x32
		}
		if len(x.WasmByteCode) > 0 {
			i -= len(x.WasmByteCode)
			copy(dAtA[i:], x.WasmByteCode)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.WasmByteCode)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Creator) > 0 {
			i -= len(x.Creator)
			copy(dAtA[i:], x.Creator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Creator)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Authority) > 0 {
			i -= len(x.Authority)
			copy(dAtA[i:], x.Authority)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Authority)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*MsgStoreCodeAdmin)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: MsgStoreCodeAdmin: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: MsgStoreCodeAdmin: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Authority = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Creator = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field WasmByteCode", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.WasmByteCode = append(x.WasmByteCode[:0], dAtA[iNdEx:postIndex]...)
				if x.WasmByteCode == nil {
					x.WasmByteCode = []byte{}
				}
				iNdEx = postIndex
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field InstantiatePermission", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.InstantiatePermission == nil {
					x.InstantiatePermission = &v1.AccessConfig{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.InstantiatePermission); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_MsgStoreCodeAdminResponse          protoreflect.MessageDescriptor
	fd_MsgStoreCodeAdminResponse_code_id  protoreflect.FieldDescriptor
	fd_MsgStoreCodeAdminResponse_checksum protoreflect.FieldDescriptor
)

func init() {
	file_miniwasm_wasmextension_v1_tx_proto_init()
	md_MsgStoreCodeAdminResponse = File_miniwasm_wasmextension_v1_tx_proto.Messages().ByName("MsgStoreCodeAdminResponse")
	fd_MsgStoreCodeAdminResponse_code_id = md_MsgStoreCodeAdminResponse.Fields().ByName("code_id")
	fd_MsgStoreCodeAdminResponse_checksum = md_MsgStoreCodeAdminResponse.Fields().ByName("checksum")
}

var _ protoreflect.Message = (*fastReflection_MsgStoreCodeAdminResponse)(nil)

type fastReflection_MsgStoreCodeAdminResponse MsgStoreCodeAdminResponse

func (x *MsgStoreCodeAdminResponse) ProtoReflect() protoreflect.Message {
	return (*fastReflection_MsgStoreCodeAdminResponse)(x)
}

func (x *MsgStoreCodeAdminResponse) slowProtoReflect() protoreflect.Message {
	mi := &file_miniwasm_wasmextension_v1_tx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_MsgStoreCodeAdminResponse_messageType fastReflection_MsgStoreCodeAdminResponse_messageType
var _ protoreflect.MessageType = fastReflection_MsgStoreCodeAdminResponse_messageType{}

type fastReflection_MsgStoreCodeAdminResponse_messageType struct{}

func (x fastReflection_MsgStoreCodeAdminResponse_messageType) Zero() protoreflect.Message {
	return (*fastReflection_MsgStoreCodeAdminResponse)(nil)
}
func (x fastReflection_MsgStoreCodeAdminResponse_messageType) New() protoreflect.Message {
	return new(fastReflection_MsgStoreCodeAdminResponse)
}
func (x fastReflection_MsgStoreCodeAdminResponse_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_MsgStoreCodeAdminResponse
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_MsgStoreCodeAdminResponse) Descriptor() protoreflect.MessageDescriptor {
	return md_MsgStoreCodeAdminResponse
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_MsgStoreCodeAdminResponse) Type() protoreflect.MessageType {
	return _fastReflection_MsgStoreCodeAdminResponse_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_MsgStoreCodeAdminResponse) New() protoreflect.Message {
	return new(fastReflection_MsgStoreCodeAdminResponse)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_MsgStoreCodeAdminResponse) Interface() protoreflect.ProtoMessage {
	return (*MsgStoreCodeAdminResponse)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_MsgStoreCodeAdminResponse) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.CodeId != uint64(0) {
		value := protoreflect.ValueOfUint64(x.CodeId)
		if !f(fd_MsgStoreCodeAdminResponse_code_id, value) {
			return
		}
	}
	if len(x.Checksum) != 0 {
		value := protoreflect.ValueOfBytes(x.Checksum)
		if !f(fd_MsgStoreCodeAdminResponse_checksum, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_MsgStoreCodeAdminResponse) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse.code_id":
		return x.CodeId != uint64(0)
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse.checksum":
		return len(x.Checksum) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse"))
		}
		panic(fmt.Errorf("message miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MsgStoreCodeAdminResponse) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse.code_id":
		x.CodeId = uint64(0)
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse.checksum":
		x.Checksum = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse"))
		}
		panic(fmt.Errorf("message miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_MsgStoreCodeAdminResponse) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse.code_id":
		value := x.CodeId
		return protoreflect.ValueOfUint64(value)
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse.checksum":
		value := x.Checksum
		return protoreflect.ValueOfBytes(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse"))
		}
		panic(fmt.Errorf("message miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MsgStoreCodeAdminResponse) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse.code_id":
		x.CodeId = value.Uint()
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse.checksum":
		x.Checksum = value.Bytes()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse"))
		}
		panic(fmt.Errorf("message miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MsgStoreCodeAdminResponse) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse.code_id":
		panic(fmt.Errorf("field code_id of message miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse is not mutable"))
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse.checksum":
		panic(fmt.Errorf("field checksum of message miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse"))
		}
		panic(fmt.Errorf("message miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_MsgStoreCodeAdminResponse) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse.code_id":
		return protoreflect.ValueOfUint64(uint64(0))
	case "miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse.checksum":
		return protoreflect.ValueOfBytes(nil)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse"))
		}
		panic(fmt.Errorf("message miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_MsgStoreCodeAdminResponse) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_MsgStoreCodeAdminResponse) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_MsgStoreCodeAdminResponse) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_MsgStoreCodeAdminResponse) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_MsgStoreCodeAdminResponse) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*MsgStoreCodeAdminResponse)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.CodeId != 0 {
			n += 1 + runtime.Sov(uint64(x.CodeId))
		}
		l = len(x.Checksum)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*MsgStoreCodeAdminResponse)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Checksum) > 0 {
			i -= len(x.Checksum)
			copy(dAtA[i:], x.Checksum)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Checksum)))
			i--
			dAtA[i] = 0x12
		}
		if x.CodeId != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.CodeId))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*MsgStoreCodeAdminResponse)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: MsgStoreCodeAdminResponse: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: MsgStoreCodeAdminResponse: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field CodeId", wireType)
				}
				x.CodeId = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.CodeId |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Checksum", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Checksum = append(x.Checksum[:0], dAtA[iNdEx:postIndex]...)
				if x.Checksum == nil {
					x.Checksum = []byte{}
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: miniwasm/wasmextension/v1/tx.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgStoreCodeAdmin submit Wasm code to the system with admin permission
type MsgStoreCodeAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Authority is the actor that signed the messages
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// Creator is the actor that created the code
	Creator string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	// WASMByteCode can be raw or gzip compressed
	WasmByteCode []byte `protobuf:"bytes,3,opt,name=wasm_byte_code,json=wasmByteCode,proto3" json:"wasm_byte_code,omitempty"`
	// InstantiatePermission access control to apply on contract creation,
	// optional
	InstantiatePermission *v1.AccessConfig `protobuf:"bytes,6,opt,name=instantiate_permission,json=instantiatePermission,proto3" json:"instantiate_permission,omitempty"`
}

func (x *MsgStoreCodeAdmin) Reset() {
	*x = MsgStoreCodeAdmin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_miniwasm_wasmextension_v1_tx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgStoreCodeAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgStoreCodeAdmin) ProtoMessage() {}

// Deprecated: Use MsgStoreCodeAdmin.ProtoReflect.Descriptor instead.
func (*MsgStoreCodeAdmin) Descriptor() ([]byte, []int) {
	return file_miniwasm_wasmextension_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgStoreCodeAdmin) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgStoreCodeAdmin) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgStoreCodeAdmin) GetWasmByteCode() []byte {
	if x != nil {
		return x.WasmByteCode
	}
	return nil
}

func (x *MsgStoreCodeAdmin) GetInstantiatePermission() *v1.AccessConfig {
	if x != nil {
		return x.InstantiatePermission
	}
	return nil
}

// MsgStoreCodeAdminResponse returns store result data.
type MsgStoreCodeAdminResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// CodeID is the reference to the stored WASM code
	CodeId uint64 `protobuf:"varint,1,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
	// Checksum is the sha256 hash of the stored code
	Checksum []byte `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
}

func (x *MsgStoreCodeAdminResponse) Reset() {
	*x = MsgStoreCodeAdminResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_miniwasm_wasmextension_v1_tx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgStoreCodeAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgStoreCodeAdminResponse) ProtoMessage() {}

// Deprecated: Use MsgStoreCodeAdminResponse.ProtoReflect.Descriptor instead.
func (*MsgStoreCodeAdminResponse) Descriptor() ([]byte, []int) {
	return file_miniwasm_wasmextension_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgStoreCodeAdminResponse) GetCodeId() uint64 {
	if x != nil {
		return x.CodeId
	}
	return 0
}

func (x *MsgStoreCodeAdminResponse) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

var File_miniwasm_wasmextension_v1_tx_proto protoreflect.FileDescriptor

var file_miniwasm_wasmextension_v1_tx_proto_rawDesc = []byte{
	0x0a, 0x22, 0x6d, 0x69, 0x6e, 0x69, 0x77, 0x61, 0x73, 0x6d, 0x2f, 0x77, 0x61, 0x73, 0x6d, 0x65,
	0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x78, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x6d, 0x69, 0x6e, 0x69, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x77,
	0x61, 0x73, 0x6d, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x1a,
	0x1e, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x76, 0x31, 0x62,
	0x65, 0x74, 0x61, 0x31, 0x2f, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x17, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x6d,
	0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c,
	0x63, 0x6f, 0x73, 0x6d, 0x77, 0x61, 0x73, 0x6d, 0x2f, 0x77, 0x61, 0x73, 0x6d, 0x2f, 0x76, 0x31,
	0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x63, 0x6f,
	0x73, 0x6d, 0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x2f, 0x61,
	0x6d, 0x69, 0x6e, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xce, 0x02, 0x0a, 0x11, 0x4d,
	0x73, 0x67, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x12, 0x36, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x18, 0xd2, 0xb4, 0x2d, 0x14, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x09, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x32, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x18, 0xd2, 0xb4, 0x2d, 0x14, 0x63,
	0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x36, 0x0a, 0x0e,
	0x77, 0x61, 0x73, 0x6d, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x42, 0x10, 0xe2, 0xde, 0x1f, 0x0c, 0x57, 0x41, 0x53, 0x4d, 0x42, 0x79,
	0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0c, 0x77, 0x61, 0x73, 0x6d, 0x42, 0x79, 0x74, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x55, 0x0a, 0x16, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x69,
	0x61, 0x74, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x77, 0x61, 0x73, 0x6d, 0x2e,
	0x77, 0x61, 0x73, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x15, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x69, 0x61, 0x74,
	0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x3a, 0x32, 0x82, 0xe7, 0xb0,
	0x2a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x8a, 0xe7, 0xb0, 0x2a, 0x1f,
	0x77, 0x61, 0x73, 0x6d, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x4d, 0x73,
	0x67, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4a,
	0x04, 0x08, 0x04, 0x10, 0x05, 0x4a, 0x04, 0x08, 0x05, 0x10, 0x06, 0x22, 0x5c, 0x0a, 0x19, 0x4d,
	0x73, 0x67, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x07, 0x63, 0x6f, 0x64, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x0a, 0xe2, 0xde, 0x1f, 0x06, 0x43,
	0x6f, 0x64, 0x65, 0x49, 0x44, 0x52, 0x06, 0x63, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x32, 0x82, 0x01, 0x0a, 0x03, 0x4d, 0x73,
	0x67, 0x12, 0x74, 0x0a, 0x0e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x12, 0x2c, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x77,
	0x61, 0x73, 0x6d, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x4d, 0x73, 0x67, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x1a, 0x34, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x77, 0x61, 0x73,
	0x6d, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73,
	0x67, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x05, 0x80, 0xe7, 0xb0, 0x2a, 0x01, 0x42, 0xee,
	0x01, 0xc8, 0xe1, 0x1e, 0x00, 0x0a, 0x1d, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x77,
	0x61, 0x73, 0x6d, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x2e, 0x76, 0x31, 0x42, 0x07, 0x54, 0x78, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x3a, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x6d, 0x69, 0x6e, 0x69, 0x77, 0x61, 0x73, 0x6d, 0x2f, 0x77, 0x61, 0x73, 0x6d, 0x65,
	0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x77, 0x61, 0x73, 0x6d,
	0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4d, 0x57,
	0x58, 0xaa, 0x02, 0x19, 0x4d, 0x69, 0x6e, 0x69, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x57, 0x61, 0x73,
	0x6d, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x19,
	0x4d, 0x69, 0x6e, 0x69, 0x77, 0x61, 0x73, 0x6d, 0x5c, 0x57, 0x61, 0x73, 0x6d, 0x65, 0x78, 0x74,
	0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x25, 0x4d, 0x69, 0x6e, 0x69,
	0x77, 0x61, 0x73, 0x6d, 0x5c, 0x57, 0x61, 0x73, 0x6d, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69,
	0x6f, 0x6e, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x1b, 0x4d, 0x69, 0x6e, 0x69, 0x77, 0x61, 0x73, 0x6d, 0x3a, 0x3a, 0x57, 0x61,
	0x73, 0x6d, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x3a, 0x3a, 0x56, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_miniwasm_wasmextension_v1_tx_proto_rawDescOnce sync.Once
	file_miniwasm_wasmextension_v1_tx_proto_rawDescData = file_miniwasm_wasmextension_v1_tx_proto_rawDesc
)

func file_miniwasm_wasmextension_v1_tx_proto_rawDescGZIP() []byte {
	file_miniwasm_wasmextension_v1_tx_proto_rawDescOnce.Do(func() {
		file_miniwasm_wasmextension_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(file_miniwasm_wasmextension_v1_tx_proto_rawDescData)
	})
	return file_miniwasm_wasmextension_v1_tx_proto_rawDescData
}

var file_miniwasm_wasmextension_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_miniwasm_wasmextension_v1_tx_proto_goTypes = []interface{}{
	(*MsgStoreCodeAdmin)(nil),         // 0: miniwasm.wasmextension.v1.MsgStoreCodeAdmin
	(*MsgStoreCodeAdminResponse)(nil), // 1: miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse
	(*v1.AccessConfig)(nil),           // 2: cosmwasm.wasm.v1.AccessConfig
}
var file_miniwasm_wasmextension_v1_tx_proto_depIdxs = []int32{
	2, // 0: miniwasm.wasmextension.v1.MsgStoreCodeAdmin.instantiate_permission:type_name -> cosmwasm.wasm.v1.AccessConfig
	0, // 1: miniwasm.wasmextension.v1.Msg.StoreCodeAdmin:input_type -> miniwasm.wasmextension.v1.MsgStoreCodeAdmin
	1, // 2: miniwasm.wasmextension.v1.Msg.StoreCodeAdmin:output_type -> miniwasm.wasmextension.v1.MsgStoreCodeAdminResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_miniwasm_wasmextension_v1_tx_proto_init() }
func file_miniwasm_wasmextension_v1_tx_proto_init() {
	if File_miniwasm_wasmextension_v1_tx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_miniwasm_wasmextension_v1_tx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgStoreCodeAdmin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_miniwasm_wasmextension_v1_tx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgStoreCodeAdminResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_miniwasm_wasmextension_v1_tx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_miniwasm_wasmextension_v1_tx_proto_goTypes,
		DependencyIndexes: file_miniwasm_wasmextension_v1_tx_proto_depIdxs,
		MessageInfos:      file_miniwasm_wasmextension_v1_tx_proto_msgTypes,
	}.Build()
	File_miniwasm_wasmextension_v1_tx_proto = out.File
	file_miniwasm_wasmextension_v1_tx_proto_rawDesc = nil
	file_miniwasm_wasmextension_v1_tx_proto_goTypes = nil
	file_miniwasm_wasmextension_v1_tx_proto_depIdxs = nil
}
