name: Build Darwin AMD64

on:
  workflow_call:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'

      - name: Set environment variables
        run: |
          MINIWASM_NETWORK_NAME="miniwasm-1"
          echo "MINIWASM_NETWORK_NAME=${MINIWASM_NETWORK_NAME}" >> $GITHUB_ENV        
          echo "GOARCH=amd64" >> $GITHUB_ENV
          echo "GOOS=darwin" >> $GITHUB_ENV
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION="v0.0.0-${GITHUB_SHA::8}"
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "ARCH_NAME=x86_64" >> $GITHUB_ENV
          WASMVM_VERSION=$(go list -m github.com/CosmWasm/wasmvm/v2 | awk '{print $2}')
          echo "WASMVM_VERSION=${WASMVM_VERSION}" >> $GITHUB_ENV 

      - name: Ensure dependencies
        run: |
          go mod tidy
          go get github.com/CosmWasm/wasmvm/v2@${WASMVM_VERSION}

      - name: Print environment variables
        run: |
          echo "GOARCH=${GOARCH}"
          echo "GOOS=${GOOS}"
          echo "VERSION=${VERSION}"
          echo "ARCH_NAME=${ARCH_NAME}"
          echo "WASMVM_VERSION=${WASMVM_VERSION}"
          echo "MINIWASM_NETWORK_NAME=${MINIWASM_NETWORK_NAME}"



      - name: Build and Package for Darwin ADM642
        run: |
          cd ../miniwasm \
          && make build \
          && cd ./build \
          && ls ~/go/pkg/mod/github.com/ \
          && ls ~/go/pkg/mod/github.com/\!cosm\!wasm/ \
          && cp ~/go/pkg/mod/github.com/\!cosm\!wasm/wasmvm/v2@${WASMVM_VERSION}/internal/api/libwasmvm.dylib ./ \
          && tar -czvf miniwasm_"$VERSION"_Darwin_"$ARCH_NAME".tar.gz ./minitiad libwasmvm.dylib \
          && mv ./miniwasm_"$VERSION"_Darwin_"$ARCH_NAME".tar.gz $GITHUB_WORKSPACE/ \
          && rm -rf ./libwasmvm.dylib ./minitiad   

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            miniwasm_${{ env.VERSION }}_Darwin_${{ env.ARCH_NAME }}.tar.gz
